
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.domgen.plan.services._1_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-02T15:47:12.629+08:00
 * Generated source version: 3.0.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "PlanService",
                      portName = "PlanServiceSoapPort",
                      targetNamespace = "http://domgen.com/plan/services/1_0",
                      wsdlLocation = "PlanServices.wsdl",
                      endpointInterface = "com.domgen.plan.services._1_0.IPlanService")
                      
public class PlanServiceSoapPortImpl implements IPlanService {

    private static final Logger LOG = Logger.getLogger(PlanServiceSoapPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.domgen.plan.services._1_0.IPlanService#getPlanRate(com.domgen.plan.schema._1_0.GetPlanRateRequest  parameters )*
     */
    public com.domgen.plan.schema._1_0.GetPlanRateResponse getPlanRate(com.domgen.plan.schema._1_0.GetPlanRateRequest parameters) throws GetPlanRateFault    { 
        LOG.info("Executing operation getPlanRate");
        System.out.println(parameters);
        try {
            com.domgen.plan.schema._1_0.GetPlanRateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new GetPlanRateFault("GetPlanRateFault...");
    }

    /* (non-Javadoc)
     * @see com.domgen.plan.services._1_0.IPlanService#validatePlanDetails(com.domgen.plan.schema._1_0.ValidatePlanDetailsRequest  parameters )*
     */
    public com.domgen.plan.schema._1_0.ValidatePlanDetailsResponse validatePlanDetails(com.domgen.plan.schema._1_0.ValidatePlanDetailsRequest parameters) throws ValidatePlanDetailsFault    { 
        LOG.info("Executing operation validatePlanDetails");
        System.out.println(parameters);
        try {
            com.domgen.plan.schema._1_0.ValidatePlanDetailsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ValidatePlanDetailsFault("ValidatePlanDetailsFault...");
    }

    /* (non-Javadoc)
     * @see com.domgen.plan.services._1_0.IPlanService#getRatesByCallSource(com.domgen.plan.schema._1_0.GetRatesByCallSourceRequest  parameters )*
     */
    public com.domgen.plan.schema._1_0.GetRatesByCallSourceResponse getRatesByCallSource(com.domgen.plan.schema._1_0.GetRatesByCallSourceRequest parameters) throws GetRatesByCallSourceFault    { 
        LOG.info("Executing operation getRatesByCallSource");
        System.out.println(parameters);
        try {
            com.domgen.plan.schema._1_0.GetRatesByCallSourceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new GetRatesByCallSourceFault("GetRatesByCallSourceFault...");
    }

    /* (non-Javadoc)
     * @see com.domgen.plan.services._1_0.IPlanService#createPlan(com.domgen.plan.schema._1_0.CreatePlanRequest  parameters )*
     */
    public com.domgen.plan.schema._1_0.CreatePlanResponse createPlan(com.domgen.plan.schema._1_0.CreatePlanRequest parameters) throws CreatePlanFault    { 
        LOG.info("Executing operation createPlan");
        System.out.println(parameters);
        try {
            com.domgen.plan.schema._1_0.CreatePlanResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CreatePlanFault("CreatePlanFault...");
    }

}
