
package com.domgen.plan.services._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-02T15:47:12.628+08:00
 * Generated source version: 3.0.2
 */

@WebFault(name = "CreatePlanFault", targetNamespace = "http://domgen.com/plan/services/1_0")
public class CreatePlanFault extends Exception {
    
    private com.domgen.plan.services._1_0.FaultType createPlanFault;

    public CreatePlanFault() {
        super();
    }
    
    public CreatePlanFault(String message) {
        super(message);
    }
    
    public CreatePlanFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CreatePlanFault(String message, com.domgen.plan.services._1_0.FaultType createPlanFault) {
        super(message);
        this.createPlanFault = createPlanFault;
    }

    public CreatePlanFault(String message, com.domgen.plan.services._1_0.FaultType createPlanFault, Throwable cause) {
        super(message, cause);
        this.createPlanFault = createPlanFault;
    }

    public com.domgen.plan.services._1_0.FaultType getFaultInfo() {
        return this.createPlanFault;
    }
}
