
package com.domgen.plan.services._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-02T15:47:12.599+08:00
 * Generated source version: 3.0.2
 */

@WebFault(name = "GetPlanRateFault", targetNamespace = "http://domgen.com/plan/services/1_0")
public class GetPlanRateFault extends Exception {
    
    private com.domgen.plan.services._1_0.FaultType getPlanRateFault;

    public GetPlanRateFault() {
        super();
    }
    
    public GetPlanRateFault(String message) {
        super(message);
    }
    
    public GetPlanRateFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetPlanRateFault(String message, com.domgen.plan.services._1_0.FaultType getPlanRateFault) {
        super(message);
        this.getPlanRateFault = getPlanRateFault;
    }

    public GetPlanRateFault(String message, com.domgen.plan.services._1_0.FaultType getPlanRateFault, Throwable cause) {
        super(message, cause);
        this.getPlanRateFault = getPlanRateFault;
    }

    public com.domgen.plan.services._1_0.FaultType getFaultInfo() {
        return this.getPlanRateFault;
    }
}
