
package com.domgen.plan.services._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-02T15:47:12.616+08:00
 * Generated source version: 3.0.2
 */

@WebFault(name = "GetRatesByCallSourceFault", targetNamespace = "http://domgen.com/plan/services/1_0")
public class GetRatesByCallSourceFault extends Exception {
    
    private com.domgen.plan.services._1_0.FaultType getRatesByCallSourceFault;

    public GetRatesByCallSourceFault() {
        super();
    }
    
    public GetRatesByCallSourceFault(String message) {
        super(message);
    }
    
    public GetRatesByCallSourceFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetRatesByCallSourceFault(String message, com.domgen.plan.services._1_0.FaultType getRatesByCallSourceFault) {
        super(message);
        this.getRatesByCallSourceFault = getRatesByCallSourceFault;
    }

    public GetRatesByCallSourceFault(String message, com.domgen.plan.services._1_0.FaultType getRatesByCallSourceFault, Throwable cause) {
        super(message, cause);
        this.getRatesByCallSourceFault = getRatesByCallSourceFault;
    }

    public com.domgen.plan.services._1_0.FaultType getFaultInfo() {
        return this.getRatesByCallSourceFault;
    }
}
