
package com.domgen.plan.services._1_0;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-02T15:47:12.676+08:00
 * Generated source version: 3.0.2
 * 
 */
 
public class IPlanService_PlanServiceSoapPort_Server{

    protected IPlanService_PlanServiceSoapPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new PlanServiceSoapPortImpl();
        String address = "http://localhost:7800/planServicesWeb/PlanService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IPlanService_PlanServiceSoapPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
