
package com.domgen.plan.services._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-02T15:47:12.609+08:00
 * Generated source version: 3.0.2
 */

@WebFault(name = "ValidatePlanDetailsFault", targetNamespace = "http://domgen.com/plan/services/1_0")
public class ValidatePlanDetailsFault extends Exception {
    
    private com.domgen.plan.services._1_0.FaultType validatePlanDetailsFault;

    public ValidatePlanDetailsFault() {
        super();
    }
    
    public ValidatePlanDetailsFault(String message) {
        super(message);
    }
    
    public ValidatePlanDetailsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidatePlanDetailsFault(String message, com.domgen.plan.services._1_0.FaultType validatePlanDetailsFault) {
        super(message);
        this.validatePlanDetailsFault = validatePlanDetailsFault;
    }

    public ValidatePlanDetailsFault(String message, com.domgen.plan.services._1_0.FaultType validatePlanDetailsFault, Throwable cause) {
        super(message, cause);
        this.validatePlanDetailsFault = validatePlanDetailsFault;
    }

    public com.domgen.plan.services._1_0.FaultType getFaultInfo() {
        return this.validatePlanDetailsFault;
    }
}
